service: serverless-rest-api
provider:
  name: aws
  runtime: go1.x
  region: us-east-1
  stage: ${opt:stage}
functions:
  api:
    handler: bin/main
    events:
      - http:
          path: /test
          method: GET
package:
  patterns:
    - "!*/**"
    - bin/main
